### ISSUE TITLE
关于论文有5个疑问

### ISSUE THREAD

**Issue by aleeyang** [KunyuLin/XOV-Action#1]
您好，关于论文，有5个疑问，向您请教下（以下是我片面的认识）

(1) Close-set 和training set标签一致，但是open-set和training set类别不一致，这个是如何进行预测对应类别的呢，是通过prompt吗？
(2)测试的时候，如何进行测试呢(一般action 使用的是分类头进行预测，CLIP中使用的是prompt)
(3)我对训练和测试的理解是： 训练阶段‘使用带有场景的text’ 和video进行学习，在测试阶段直接使用没有带场景的text的prompt
(4)对于训练没有见过的动作（open-set），使用prompt 能输出对应的label吗？（之前这个label，在训练的时候都没有出现，真的好神奇）
(5) discrimination loss 和 consistency loss 从整体来理解，前者是将相同的类别但不同的场景分开，后者是将将相同的类别但不同的场景来进，两者似乎有点矛盾
以上可能是我有误解的地方，希望作者能不吝赐教

**Comment by KunyuLin** [comment]
您好，感谢您对我们工作的关注，以下是对您五个问题的回复：

前四个问题是关于open-vocabulary action recognition任务设定的疑问。简单来讲，现有的open-vocabulary action recognition方法大多是基于finetune或adapt CLIP的范式来做的，使用的是一种类似CLIP的image/video-text matching的方式来完成训练，并基于action类别的label text完成测试阶段的类别预测。以下是对您每个问题的具体回答：
（1）在测试阶段，模型会拿到open-set类别的label text，并根据label text构建prompt、提取文本特征，之后使用视频特征与所有类别的文本特征计算相似度，相似度最高的即为预测类别；
（2）测试时候使用的是类似CLIP的做法，请参考问题（1）的回复；
（3）训练和测试阶段都会使用“没有带场景的text”的prompt，训练阶段会使用额外的“带有场景的text”的prompt；
（4）虽然训练时没有见过open-set类别，但模型是基于CLIP的image/video-text matching范式完成训练的，因此测试时可以通过匹配open-set类别的类别名称完成预测，即利用视频和文本特征空间相匹配这一特性。

如果您需要了解更多、更深入的细节，您可以参考之前一些工作的代码，例如[ActionCLIP](https://github.com/sallymmx/ActionCLIP)、[ViFi-CLIP](https://github.com/muzairkhattak/ViFi-CLIP)和[Open-VCLIP](https://github.com/wengzejia1/Open-VCLIP)。

第五个问题是关于loss设计的疑问。您可能对我们的方法有一定误解，事实上我们的两个loss并不是矛盾的。
（5）我们的discrimination loss的作用是扩大视频特征与*带有场景的同类别action text*的距离，而不是您说的“将相同的类别但不同的场景分开”；我们的consistency loss的作用是*相对于其他类别的action text*，缩小视频特征与*带有场景的同类别action text*的距离，而不是您说的“将相同的类别但不同的场景拉近”。
我猜测您可能认为“扩大距离”和“缩小距离”这两种作用在宏观上存在矛盾，但我们的consistency loss在设计时引入了“*相对于其他类别的action text*”的约束（而discrimination loss没有），因此它们实际上并不冲突。这两个loss一起使用时很好地控制了视频在特征空间中的位置，即一个视频与各种类型action text的距离应该满足“不带场景的同类别action text < 带有场景的同类别action text < 其他类别的action text”的约束，这是非常合理的。

您可以查看我们论文的实验部分，我们对这两个loss的作用进行了一些实验分析，实验结果证明我们的discrimination loss主要提高的是closed-set性能，我们的consistency loss主要提高的是open-set性能。我们将会在论文的下一个版本提供更多的实验分析。

希望以上回答能够解决您的疑惑。如果有其他疑问，欢迎讨论。再次感谢您对我们工作的关注。

**Comment by aleeyang** [comment]
感谢你详细的解释，我理解清楚了，感谢！
